# Generated by Django 4.2.4 on 2023-08-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0017_repairs_client_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='serv_mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(null=True, upload_to='static/images/avatars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
