# Generated by Django 4.2.4 on 2023-08-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0018_serv_mechanic_remove_client_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serv_mechanic',
            new_name='Mechanic',
        ),
    ]
