# Generated by Django 4.2.4 on 2023-08-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0019_rename_serv_mechanic_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='avatar',
            field=models.ImageField(default='garage_django/static/images/default_avatar.png', upload_to='static/images/avatars'),
        ),
    ]
